# Generated by Django 4.2.15 on 2024-09-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
